#!/bin/bash

set -eu

this_dir="$(dirname "$0")"

PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

in_uid='1000'
in_gid='1000'
in_tz='Asia/Tokyo'

ln -sf "/usr/share/zoneinfo/$in_tz" /etc/localtime && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tzdata

###

rm -rf /etc/skel/.??*
rm -rf /etc/skel/*
mkdir -m 700 /etc/skel/.ssh
if ! grep -qs '[^:]*:[^:]*:'$in_gid':' /etc/group; then
    addgroup --gid $in_gid ubuntu
fi
useradd --uid $in_uid --gid $in_gid --create-home --shell /bin/bash --no-log-init --password '*' ubuntu
    # use useradd instead of adduser to avoid bugs of Docker on Mac for
    # handling big sparse files (/var/log/lastlog in this case).
    # the option '--no-log-init' is the key.
    # see https://github.com/docker/docker/issues/5419
adduser ubuntu sudo
adduser ubuntu adm
echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu

###

cat <<'^Z' | sudo -Hsu ubuntu
cd
mkdir t t/project
cd t
cat <<'^^Z' > App.scala
object App {
  def main(args: Array[String]): Unit = {
    println("Hello, world!")
  }
}
^^Z
cat <<'^^Z' > build.sbt
lazy val a = project in file(".")
scalaVersion := "2.11.11"
^^Z
cat <<'^^Z' > project/build.properties
sbt.version=0.13.15
^^Z
while ! yes q | sbt update; do
    :
done
while ! yes q | sbt compile; do
    :
done
cd
rm -rf t
^Z

